Linting changes made to all controllers in the organisation folder
heritagefund/funding-frontend pull request #471
Opened 2020-08-28 13:06 UTC by ptrelease

Linting changes made.

Rubocop only reports warnings now.  And RSpec runs without errors. Manaully tested the organisation pages and found no errors.

2020-08-28 13:08 UTC, ptrelease commented on app/controllers/organisation/numbers_controller.rb
I could have broken the string up.  But I figured one us would try and put it back to a single statement - then encounter this again.

2020-09-01 06:34 UTC, stuartmccoll requested changes

2020-09-01 06:34 UTC, stuartmccoll commented on app/controllers/organisation/mission_controller.rb
> +    params.merge!({ organisation: { mission: '' } }) if params[:organisation].blank?
```suggestion
    params.merge!({ organisation: { mission: '' } }) unless params[:organisation].present?
```

I'm not convinced by the change in logic here - we've kept to `.present?` elsewhere when addressing RuboCop violations.

I'll test locally and then commit the suggestion if it doesn't re-trigger a violation.

2020-09-01 06:34 UTC, stuartmccoll commented on app/controllers/organisation/numbers_controller.rb
I think we should be fine to just put the first line in `'`'s and then the second line in `"`'s. I'll test locally and remove the RuboCop comments if so.

2020-09-01 06:43 UTC, stuartmccoll commented on app/controllers/organisation/numbers_controller.rb
Tested locally and this works as expected.

2020-09-01 06:44 UTC, stuartmccoll approved these changes

2020-09-01 06:48 UTC, merged