[WIP] contact duplicate checks
heritagefund/funding-frontend pull request #606
Opened 2021-03-09 15:50 UTC by ptrelease

2021-03-10 08:42 UTC, stuartmccoll requested changes

2021-03-10 08:42 UTC, stuartmccoll commented on lib/apis/salesforce/salesforce_api.rb
> +          @client.query_all("select Id from Contact where name = '#{user.name}' and Email = '#{user.email}' ")
```suggestion
          @client.query_all("select Id from Contact where name = '#{user.name}' and Email = '#{user.email}'")
```

2021-03-10 08:42 UTC, stuartmccoll commented on lib/apis/salesforce/salesforce_api.rb
> +    # Retries accounted for in outer scope call.
Should this read as `Calling function should handle exceptions/retries`? That way it's clear to anybody attempting to re-use this method elsewhere that they need to account for this.

2021-03-10 08:42 UTC, stuartmccoll commented on lib/apis/salesforce/salesforce_api.rb
> +    # Retries accounted for in outer scope call.
Should this read as `Calling function should handle exceptions/retries`? That way it's clear to anybody attempting to re-use this method elsewhere that they need to account for this.

2021-03-10 08:51 UTC, ptrelease commented on lib/apis/salesforce/salesforce_api.rb
> +    def find_an_existing_contact_matching_this_user(user)
find_matching_contact_for_user is fine.  Will change.

2021-03-10 08:55 UTC, ptrelease commented on lib/apis/salesforce/salesforce_api.rb
> +    # Exception handling and retries accounted for in outer scope
like it

2021-03-10 09:00 UTC, ptrelease commented on lib/apis/salesforce/salesforce_api.rb
> +          @client.query_all("select Id from Contact where name = '#{user.name}' and Email = '#{user.email}' ")
I thought you'd prefer the space here ;-)

2021-03-10 09:01 UTC, ptrelease commented on lib/apis/salesforce/salesforce_api.rb
> +    # Retries accounted for in outer scope call.
Changed

2021-03-10 09:44 UTC, paulmsmith commented
@ptrelease Github tip: Did you know you can create WIP pull requests now? I think github calls them a 'draft' and they can't be merged until you say so.

2021-03-10 16:39 UTC, ptrelease commented
> @ptrelease Github tip: Did you know you can create WIP pull requests now? I think github calls them a 'draft' and they can't be merged until you say so.

2021-03-11 08:48 UTC, stuartmccoll commented on lib/apis/salesforce/salesforce_api.rb
> +      salesforce_account_id = @client.upsert!(
We don't need to assign to a variable here, as we're just returning what the `upsert` call returns.

2021-03-11 08:49 UTC, stuartmccoll commented on lib/apis/salesforce/salesforce_api.rb
> +      salesforce_account_id = @client.upsert!(
We don't need to assign to a variable here, as we're just returning what the `upsert` call returns.

2021-03-11 09:57 UTC, stuartmccoll approved these changes

2021-03-11 09:57 UTC, merged